- name: Install
  hosts: psedit
  gather_facts: false
  tasks:
      - name: Install vlc
        win_package:
          name: "Vlc Media Player"
          path: https://mirrors.estointernet.in/videolan/vlc/3.0.8/win64/vlc-3.0.8-win64.msi
          arguments: '/quiet /qn /le C:\VLCinstalllog.txt'
          product_id: "VLC media player"
          ensure: present
          creates_path: 'C:\Program Files(x86)\VideoLAN\VLC'                  
