- name: Install
  hosts: psedit
  gather_facts: false
  tasks:
      - name: Install vlc
        win_package:
         path:  https://mirrors.afghan-wireless.com/videolan/vlc/3.0.16/win64/vlc-3.0.16-win64.exe
         arguments: /S
         product_id: VLC-media-player
         creates_path: 'C:\Program Files(x86)\VideoLAN\VLC\vlc.exe'     
         e: Install
    
      - name: Install Notepad++
        win_package: 
          path: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.1.4/npp.8.1.4.Installer.x64.exe
          arguments: /S
          product_id: notepad-plus-plus
          creates_path: 'C:\Program Files (x86)\Notepad++\npp++.exe'

      - name: Install Quicktime Player
        win_package:
          path: https://secure-appldnld.apple.com/QuickTime/031-43075-20160107-C0844134-B3CD-11E5-B1C0-43CA8D551951/QuickTimeInstaller.exe
          arguments: /S
          product_id: Quicktime-Player
          creates_path: 'C:\Program Files (x86)\QuickTime\QuickTimePlayer.exe'

      - name: Install Media Info
        win_package:
          path: https://mediaarea.net/download/binary/mediainfo-gui/21.03/MediaInfo_GUI_21.03_Windows.exe
          arguments: /S
          product_id: Media-Info
          creates_path: 'C:\Program Files\MediaInfo\MediaInfo.exe'

      - name: Install Imageglass
        win_package:
          path: https://imageglass.org/release/imageglass-8-2-6-6-june-56/download
          arguments: /S
          product_id: Imageglass
          creates_path: 'C:\Program Files\ImageGlass\ImageGlass.exe'
